#!/usr/bin/env node
/**
 * Import a word list into the multi-user schema (supabase/migrations/).
 *
 * Two output modes:
 *
 *   node pipeline/import.mjs words.csv                 # emit SQL to stdout
 *   node pipeline/import.mjs words.csv --out seed.sql  # emit SQL to a file
 *   node pipeline/import.mjs words.csv --apply         # push to Supabase
 *
 * SQL emission is the default so the pipeline is runnable and reviewable with no
 * credentials at all — the generated file can be read, diffed, and applied by
 * hand. `--apply` needs SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY: row-level
 * security grants clients no insert on content tables, by design, so writes go
 * through the service role.
 *
 * Expected CSV columns (only `word` is required):
 *   word, part_of_speech, definition, definition_reading_level, sample_sentence,
 *   ipa, tts_override_text, language_of_origin, homophone_group, frequency_rank,
 *   age_gated, list_band, source, license
 */

import { readFileSync, writeFileSync } from "node:fs";
import { parse } from "csv-parse/sync";
import { enrichWord } from "./lib/enrich.mjs";

const COLUMNS = [
  "word", "part_of_speech", "definition", "definition_reading_level",
  "sample_sentence", "sentence_mask_start", "sentence_mask_end", "ipa",
  "tts_override_text", "language_of_origin", "homophone_group", "syllables",
  "frequency_rank", "error_patterns", "age_gated", "source", "license",
];

function main(argv) {
  const args = argv.slice(2);
  const csvPath = args.find((a) => !a.startsWith("--"));
  if (!csvPath) {
    console.error("usage: node pipeline/import.mjs <words.csv> [--out FILE] [--apply] [--strict]");
    process.exit(2);
  }
  const apply = args.includes("--apply");
  const strict = args.includes("--strict");
  const outIdx = args.indexOf("--out");
  const outPath = outIdx === -1 ? null : args[outIdx + 1];

  const rows = parse(readFileSync(csvPath, "utf8"), {
    columns: true,
    skip_empty_lines: true,
    trim: true,
  });

  const enriched = [];
  const problems = [];
  for (const [i, row] of rows.entries()) {
    try {
      const result = enrichWord(row);
      enriched.push(result);
      for (const w of result.warnings) {
        problems.push({ line: i + 2, word: row.word, warning: w });
      }
    } catch (err) {
      problems.push({ line: i + 2, word: row.word, warning: `SKIPPED: ${err.message}` });
    }
  }

  for (const p of problems) {
    console.error(`  line ${p.line} (${p.word ?? "?"}): ${p.warning}`);
  }

  const blocking = problems.filter((p) => /SKIPPED|HOMOPHONE WITHOUT/.test(p.warning));
  if (strict && blocking.length) {
    console.error(`\n${blocking.length} blocking problem(s); --strict refuses to continue.`);
    process.exit(1);
  }

  console.error(
    `\n${enriched.length} of ${rows.length} rows enriched` +
    `, ${problems.length} warning(s)` +
    `\nbands: ${summarizeBands(enriched)}`,
  );

  if (apply) return applyToSupabase(enriched);

  const sql = toSql(enriched);
  if (outPath) {
    writeFileSync(outPath, sql);
    console.error(`\nwrote ${outPath}`);
  } else {
    process.stdout.write(sql);
  }
}

function summarizeBands(enriched) {
  const counts = new Map();
  for (const e of enriched) counts.set(e.band, (counts.get(e.band) ?? 0) + 1);
  return [...counts].sort().map(([b, n]) => `${b}=${n}`).join(" ") || "none";
}

/**
 * Emit idempotent SQL. Re-running the same file must be a no-op, so words upsert
 * on their unique spelling and list membership upserts on its composite key.
 */
function toSql(enriched) {
  const lines = [
    "-- Generated by pipeline/import.mjs. Idempotent: safe to re-run.",
    "begin;",
    "",
  ];

  for (const { word, band } of enriched) {
    const cols = COLUMNS.filter((c) => word[c] !== undefined);
    const vals = cols.map((c) => lit(word[c]));
    const updates = cols.filter((c) => c !== "word").map((c) => `${c} = excluded.${c}`);

    lines.push(
      `insert into words (${cols.join(", ")})`,
      `values (${vals.join(", ")})`,
      `on conflict (word) do update set ${updates.join(", ")};`,
      "",
      `insert into word_list_items (list_id, word_id)`,
      `select l.id, w.id from word_lists l, words w`,
      ` where l.slug = ${lit(band)} and w.word = ${lit(word.word)}`,
      `on conflict do nothing;`,
      "",
    );
  }

  lines.push("commit;", "");
  return lines.join("\n");
}

function lit(v) {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  if (Array.isArray(v)) {
    return v.length === 0
      ? "'{}'"
      : `array[${v.map((x) => lit(x)).join(", ")}]::text[]`;
  }
  return `'${String(v).replace(/'/g, "''")}'`;
}

async function applyToSupabase(enriched) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    console.error("--apply needs SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY (see .env.example)");
    process.exit(1);
  }

  const { createClient } = await import("@supabase/supabase-js");
  // supabase-js constructs a realtime client unconditionally, which wants a
  // global WebSocket. Node 22 has one; older runtimes need the `ws` shim.
  const supabase = createClient(url, key, { auth: { persistSession: false } });

  const BATCH = 200;
  for (let i = 0; i < enriched.length; i += BATCH) {
    const slice = enriched.slice(i, i + BATCH);

    const { data, error } = await supabase
      .from("words")
      .upsert(slice.map((e) => e.word), { onConflict: "word" })
      .select("id, word");
    if (error) throw new Error(`words upsert failed at row ${i}: ${error.message}`);

    const idByWord = new Map(data.map((r) => [r.word, r.id]));
    const { data: lists, error: listErr } = await supabase
      .from("word_lists")
      .select("id, slug")
      .in("slug", [...new Set(slice.map((e) => e.band))]);
    if (listErr) throw new Error(`list lookup failed: ${listErr.message}`);

    const idBySlug = new Map(lists.map((r) => [r.slug, r.id]));
    const items = slice
      .map((e) => ({ list_id: idBySlug.get(e.band), word_id: idByWord.get(e.word.word) }))
      .filter((r) => r.list_id && r.word_id);

    const { error: itemErr } = await supabase
      .from("word_list_items")
      .upsert(items, { onConflict: "list_id,word_id", ignoreDuplicates: true });
    if (itemErr) throw new Error(`list membership failed at row ${i}: ${itemErr.message}`);

    console.error(`  applied ${Math.min(i + BATCH, enriched.length)} / ${enriched.length}`);
  }
  console.error("done.");
}

main(process.argv);
